### ISSUE TITLE
Text in the button

### ISSUE THREAD

**Issue by ezhivitsa** [Kris13789/DiaperGuide#1]
Use the following css to fix the position of the text in the button:
```css
.change-diaper-btn {
  // ...
  padding: 0 40px;
  box-sizing: border-box;
  line-height: 65px;
}
```
